<?php

namespace ContainerKxOl6MZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarControllerindexService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Zo33x0q.App\Controller\CalendarController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zo33x0q.App\\Controller\\CalendarController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sessionModuleRepository' => ['privates', 'App\\Repository\\SessionModuleRepository', 'getSessionModuleRepositoryService', true],
            'utilisateurInstitutionSessionModuleRepository' => ['privates', 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository', 'getUtilisateurInstitutionSessionModuleRepositoryService', true],
            'jourHoraireRepository' => ['privates', 'App\\Repository\\JourHoraireRepository', 'getJourHoraireRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'sessionModuleRepository' => 'App\\Repository\\SessionModuleRepository',
            'utilisateurInstitutionSessionModuleRepository' => 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository',
            'jourHoraireRepository' => 'App\\Repository\\JourHoraireRepository',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\CalendarController::index()', $container);
    }
}
