<?php

namespace ContainerKxOl6MZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainScheduleService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Scheduler\MainSchedule' shared autowired service.
     *
     * @return \App\Scheduler\MainSchedule
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Scheduler\\MainSchedule'] = new \App\Scheduler\MainSchedule(($container->services['cache.app'] ?? $container->load('getCache_AppService')));
    }
}
