<?php

namespace ContainerKxOl6MZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPDFEnvoieMailhandlePdfRequestService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.nT.xDSC.App\Controller\PDF_Envoie_Mail::handlePdfRequest()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nT.xDSC.App\\Controller\\PDF_Envoie_Mail::handlePdfRequest()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'utilisateur' => ['privates', 'App\\Entity\\Utilisateur', 'getUtilisateurService', true],
            'uisRepo' => ['privates', 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository', 'getUtilisateurInstitutionSessionModuleRepositoryService', true],
            'pdfGenerator' => ['privates', 'App\\Service\\PdfGenerator', 'getPdfGeneratorService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'utilisateurRepo' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'utilisateur' => 'App\\Entity\\Utilisateur',
            'uisRepo' => 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository',
            'pdfGenerator' => 'App\\Service\\PdfGenerator',
            'mailer' => '?',
            'logger' => '?',
            'utilisateurRepo' => 'App\\Repository\\UtilisateurRepository',
        ]))->withContext('App\\Controller\\PDF_Envoie_Mail::handlePdfRequest()', $container);
    }
}
