<?php

namespace ContainerKxOl6MZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStripeWebhookControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\StripeWebhookController' shared autowired service.
     *
     * @return \App\Controller\StripeWebhookController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\StripeWebhookController'] = $instance = new \App\Controller\StripeWebhookController(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\StripeWebhookController', $container));

        return $instance;
    }
}
