<?php

namespace ContainerKxOl6MZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateurModuleRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\UtilisateurModuleRepository' shared autowired service.
     *
     * @return \App\Repository\UtilisateurModuleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\UtilisateurModuleRepository'] = new \App\Repository\UtilisateurModuleRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
