<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxOl6MZ\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxOl6MZ/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKxOl6MZ.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKxOl6MZ\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKxOl6MZ\App_KernelProdContainer([
    'container.build_hash' => 'KxOl6MZ',
    'container.build_id' => 'f9fdc95e',
    'container.build_time' => 1779125524,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxOl6MZ');
