<?php

namespace ContainerC24beQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8uOCYSmService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.8uOCYSm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8uOCYSm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'params' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'params' => '?',
        ]);
    }
}
