<?php

namespace ContainerC24beQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelDevContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CalendarController::index' => ['privates', '.service_locator.Zo33x0q.App\\Controller\\CalendarController::index()', 'getCalendarControllerindexService', true],
            'App\\Controller\\ConnexionController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\ConnexionController::login()', 'getConnexionControllerloginService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.O.hDLft.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\InscriptionController::register' => ['privates', '.service_locator.g9BceMG.App\\Controller\\InscriptionController::register()', 'getInscriptionControllerregisterService', true],
            'App\\Controller\\InstitutionController::indexEtAjouter' => ['privates', '.service_locator.MFcjO6b.App\\Controller\\InstitutionController::indexEtAjouter()', 'getInstitutionControllerindexEtAjouterService', true],
            'App\\Controller\\InstitutionController::liste' => ['privates', '.service_locator.GsSF5aC.App\\Controller\\InstitutionController::liste()', 'getInstitutionControllerlisteService', true],
            'App\\Controller\\InstitutionController::modifierRoles' => ['privates', '.service_locator.0T6sRVU.App\\Controller\\InstitutionController::modifierRoles()', 'getInstitutionControllermodifierRolesService', true],
            'App\\Controller\\InstitutionController::modifier' => ['privates', '.service_locator.6S4WW3N.App\\Controller\\InstitutionController::modifier()', 'getInstitutionControllermodifierService', true],
            'App\\Controller\\InstitutionController::modifiermodulecommentaire' => ['privates', '.service_locator._t01d57.App\\Controller\\InstitutionController::modifiermodulecommentaire()', 'getInstitutionControllermodifiermodulecommentaireService', true],
            'App\\Controller\\InvitationController::invite' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\InvitationController::invite()', 'getInvitationControllerinviteService', true],
            'App\\Controller\\InvitationController::acceptInvitation' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\InvitationController::acceptInvitation()', 'getInvitationControlleracceptInvitationService', true],
            'App\\Controller\\PDF_Envoie_Mail::handlePdfRequest' => ['privates', '.service_locator.nT.xDSC.App\\Controller\\PDF_Envoie_Mail::handlePdfRequest()', 'getPDFEnvoieMailhandlePdfRequestService', true],
            'App\\Controller\\PDF_Envoie_Mail::sendSessionPdfs' => ['privates', '.service_locator.w8YtUCL.App\\Controller\\PDF_Envoie_Mail::sendSessionPdfs()', 'getPDFEnvoieMailsendSessionPdfsService', true],
            'App\\Controller\\PDF_Envoie_Mail::sendAllPdfs' => ['privates', '.service_locator.9dMfL4L.App\\Controller\\PDF_Envoie_Mail::sendAllPdfs()', 'getPDFEnvoieMailsendAllPdfsService', true],
            'App\\Controller\\PaymentController::paymentRequired' => ['privates', '.service_locator.8uOCYSm.App\\Controller\\PaymentController::paymentRequired()', 'getPaymentControllerpaymentRequiredService', true],
            'App\\Controller\\PaymentController::createCheckoutSession' => ['privates', '.service_locator.8uOCYSm.App\\Controller\\PaymentController::createCheckoutSession()', 'getPaymentControllercreateCheckoutSessionService', true],
            'App\\Controller\\PaymentController::paymentSuccess' => ['privates', '.service_locator.7UxYh5w.App\\Controller\\PaymentController::paymentSuccess()', 'getPaymentControllerpaymentSuccessService', true],
            'App\\Controller\\SessionModuleController::index' => ['privates', '.service_locator.XYq597l.App\\Controller\\SessionModuleController::index()', 'getSessionModuleControllerindexService', true],
            'App\\Controller\\SessionModuleController::modifierSessionModule' => ['privates', '.service_locator.LceDNDN.App\\Controller\\SessionModuleController::modifierSessionModule()', 'getSessionModuleControllermodifierSessionModuleService', true],
            'App\\Controller\\SessionModuleController::modifierUtilisateurInstitutionSessionModule' => ['privates', '.service_locator.VxWxTIF.App\\Controller\\SessionModuleController::modifierUtilisateurInstitutionSessionModule()', 'getSessionModuleControllermodifierUtilisateurInstitutionSessionModuleService', true],
            'App\\Controller\\SessionModuleController::modifierSession' => ['privates', '.service_locator.CTxn2ea.App\\Controller\\SessionModuleController::modifierSession()', 'getSessionModuleControllermodifierSessionService', true],
            'App\\Controller\\SessionModuleController::modifierInstitution' => ['privates', '.service_locator.6pPFRks.App\\Controller\\SessionModuleController::modifierInstitution()', 'getSessionModuleControllermodifierInstitutionService', true],
            'App\\Controller\\SessionModuleController::modifierModule' => ['privates', '.service_locator.RvrrnGg.App\\Controller\\SessionModuleController::modifierModule()', 'getSessionModuleControllermodifierModuleService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CalendarController:index' => ['privates', '.service_locator.Zo33x0q.App\\Controller\\CalendarController::index()', 'getCalendarControllerindexService', true],
            'App\\Controller\\ConnexionController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\ConnexionController::login()', 'getConnexionControllerloginService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.O.hDLft.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\InscriptionController:register' => ['privates', '.service_locator.g9BceMG.App\\Controller\\InscriptionController::register()', 'getInscriptionControllerregisterService', true],
            'App\\Controller\\InstitutionController:indexEtAjouter' => ['privates', '.service_locator.MFcjO6b.App\\Controller\\InstitutionController::indexEtAjouter()', 'getInstitutionControllerindexEtAjouterService', true],
            'App\\Controller\\InstitutionController:liste' => ['privates', '.service_locator.GsSF5aC.App\\Controller\\InstitutionController::liste()', 'getInstitutionControllerlisteService', true],
            'App\\Controller\\InstitutionController:modifierRoles' => ['privates', '.service_locator.0T6sRVU.App\\Controller\\InstitutionController::modifierRoles()', 'getInstitutionControllermodifierRolesService', true],
            'App\\Controller\\InstitutionController:modifier' => ['privates', '.service_locator.6S4WW3N.App\\Controller\\InstitutionController::modifier()', 'getInstitutionControllermodifierService', true],
            'App\\Controller\\InstitutionController:modifiermodulecommentaire' => ['privates', '.service_locator._t01d57.App\\Controller\\InstitutionController::modifiermodulecommentaire()', 'getInstitutionControllermodifiermodulecommentaireService', true],
            'App\\Controller\\InvitationController:invite' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\InvitationController::invite()', 'getInvitationControllerinviteService', true],
            'App\\Controller\\InvitationController:acceptInvitation' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\InvitationController::acceptInvitation()', 'getInvitationControlleracceptInvitationService', true],
            'App\\Controller\\PDF_Envoie_Mail:handlePdfRequest' => ['privates', '.service_locator.nT.xDSC.App\\Controller\\PDF_Envoie_Mail::handlePdfRequest()', 'getPDFEnvoieMailhandlePdfRequestService', true],
            'App\\Controller\\PDF_Envoie_Mail:sendSessionPdfs' => ['privates', '.service_locator.w8YtUCL.App\\Controller\\PDF_Envoie_Mail::sendSessionPdfs()', 'getPDFEnvoieMailsendSessionPdfsService', true],
            'App\\Controller\\PDF_Envoie_Mail:sendAllPdfs' => ['privates', '.service_locator.9dMfL4L.App\\Controller\\PDF_Envoie_Mail::sendAllPdfs()', 'getPDFEnvoieMailsendAllPdfsService', true],
            'App\\Controller\\PaymentController:paymentRequired' => ['privates', '.service_locator.8uOCYSm.App\\Controller\\PaymentController::paymentRequired()', 'getPaymentControllerpaymentRequiredService', true],
            'App\\Controller\\PaymentController:createCheckoutSession' => ['privates', '.service_locator.8uOCYSm.App\\Controller\\PaymentController::createCheckoutSession()', 'getPaymentControllercreateCheckoutSessionService', true],
            'App\\Controller\\PaymentController:paymentSuccess' => ['privates', '.service_locator.7UxYh5w.App\\Controller\\PaymentController::paymentSuccess()', 'getPaymentControllerpaymentSuccessService', true],
            'App\\Controller\\SessionModuleController:index' => ['privates', '.service_locator.XYq597l.App\\Controller\\SessionModuleController::index()', 'getSessionModuleControllerindexService', true],
            'App\\Controller\\SessionModuleController:modifierSessionModule' => ['privates', '.service_locator.LceDNDN.App\\Controller\\SessionModuleController::modifierSessionModule()', 'getSessionModuleControllermodifierSessionModuleService', true],
            'App\\Controller\\SessionModuleController:modifierUtilisateurInstitutionSessionModule' => ['privates', '.service_locator.VxWxTIF.App\\Controller\\SessionModuleController::modifierUtilisateurInstitutionSessionModule()', 'getSessionModuleControllermodifierUtilisateurInstitutionSessionModuleService', true],
            'App\\Controller\\SessionModuleController:modifierSession' => ['privates', '.service_locator.CTxn2ea.App\\Controller\\SessionModuleController::modifierSession()', 'getSessionModuleControllermodifierSessionService', true],
            'App\\Controller\\SessionModuleController:modifierInstitution' => ['privates', '.service_locator.6pPFRks.App\\Controller\\SessionModuleController::modifierInstitution()', 'getSessionModuleControllermodifierInstitutionService', true],
            'App\\Controller\\SessionModuleController:modifierModule' => ['privates', '.service_locator.RvrrnGg.App\\Controller\\SessionModuleController::modifierModule()', 'getSessionModuleControllermodifierModuleService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CalendarController::index' => '?',
            'App\\Controller\\ConnexionController::login' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\InscriptionController::register' => '?',
            'App\\Controller\\InstitutionController::indexEtAjouter' => '?',
            'App\\Controller\\InstitutionController::liste' => '?',
            'App\\Controller\\InstitutionController::modifierRoles' => '?',
            'App\\Controller\\InstitutionController::modifier' => '?',
            'App\\Controller\\InstitutionController::modifiermodulecommentaire' => '?',
            'App\\Controller\\InvitationController::invite' => '?',
            'App\\Controller\\InvitationController::acceptInvitation' => '?',
            'App\\Controller\\PDF_Envoie_Mail::handlePdfRequest' => '?',
            'App\\Controller\\PDF_Envoie_Mail::sendSessionPdfs' => '?',
            'App\\Controller\\PDF_Envoie_Mail::sendAllPdfs' => '?',
            'App\\Controller\\PaymentController::paymentRequired' => '?',
            'App\\Controller\\PaymentController::createCheckoutSession' => '?',
            'App\\Controller\\PaymentController::paymentSuccess' => '?',
            'App\\Controller\\SessionModuleController::index' => '?',
            'App\\Controller\\SessionModuleController::modifierSessionModule' => '?',
            'App\\Controller\\SessionModuleController::modifierUtilisateurInstitutionSessionModule' => '?',
            'App\\Controller\\SessionModuleController::modifierSession' => '?',
            'App\\Controller\\SessionModuleController::modifierInstitution' => '?',
            'App\\Controller\\SessionModuleController::modifierModule' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CalendarController:index' => '?',
            'App\\Controller\\ConnexionController:login' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\InscriptionController:register' => '?',
            'App\\Controller\\InstitutionController:indexEtAjouter' => '?',
            'App\\Controller\\InstitutionController:liste' => '?',
            'App\\Controller\\InstitutionController:modifierRoles' => '?',
            'App\\Controller\\InstitutionController:modifier' => '?',
            'App\\Controller\\InstitutionController:modifiermodulecommentaire' => '?',
            'App\\Controller\\InvitationController:invite' => '?',
            'App\\Controller\\InvitationController:acceptInvitation' => '?',
            'App\\Controller\\PDF_Envoie_Mail:handlePdfRequest' => '?',
            'App\\Controller\\PDF_Envoie_Mail:sendSessionPdfs' => '?',
            'App\\Controller\\PDF_Envoie_Mail:sendAllPdfs' => '?',
            'App\\Controller\\PaymentController:paymentRequired' => '?',
            'App\\Controller\\PaymentController:createCheckoutSession' => '?',
            'App\\Controller\\PaymentController:paymentSuccess' => '?',
            'App\\Controller\\SessionModuleController:index' => '?',
            'App\\Controller\\SessionModuleController:modifierSessionModule' => '?',
            'App\\Controller\\SessionModuleController:modifierUtilisateurInstitutionSessionModule' => '?',
            'App\\Controller\\SessionModuleController:modifierSession' => '?',
            'App\\Controller\\SessionModuleController:modifierInstitution' => '?',
            'App\\Controller\\SessionModuleController:modifierModule' => '?',
        ]));
    }
}
