<?php

namespace ContainerC24beQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvitationListenerService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\EventListener\InvitationListener' shared autowired service.
     *
     * @return \App\EventListener\InvitationListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\EventListener\\InvitationListener'] = new \App\EventListener\InvitationListener();
    }
}
