<?php

namespace ContainerC24beQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_SchedulerDefaultService extends App_KernelDevContainer
{
    /*
     * Gets the private 'messenger.transport.scheduler_default' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\TransportInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['messenger.transport_factory'] ?? $container->load('getMessenger_TransportFactoryService'));

        if (isset($container->privates['messenger.transport.scheduler_default'])) {
            return $container->privates['messenger.transport.scheduler_default'];
        }

        return $container->privates['messenger.transport.scheduler_default'] = $a->createTransport('schedule://default', ['transport_name' => 'scheduler_default'], ($container->privates['messenger.transport.native_php_serializer'] ??= new \Symfony\Component\Messenger\Transport\Serialization\PhpSerializer()));
    }
}
