<?php

namespace ContainerC24beQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPDFEnvoieMailsendSessionPdfsService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.w8YtUCL.App\Controller\PDF_Envoie_Mail::sendSessionPdfs()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w8YtUCL.App\\Controller\\PDF_Envoie_Mail::sendSessionPdfs()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
            'uismRepo' => ['privates', 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository', 'getUtilisateurInstitutionSessionModuleRepositoryService', true],
            'pdfGenerator' => ['privates', 'App\\Service\\PdfGenerator', 'getPdfGeneratorService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
        ], [
            'sessionRepository' => 'App\\Repository\\SessionRepository',
            'uismRepo' => 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository',
            'pdfGenerator' => 'App\\Service\\PdfGenerator',
            'mailer' => '?',
            'logger' => '?',
        ]))->withContext('App\\Controller\\PDF_Envoie_Mail::sendSessionPdfs()', $container);
    }
}
