<?php

namespace ContainerC24beQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllerpaymentSuccessService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.7UxYh5w.App\Controller\PaymentController::paymentSuccess()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7UxYh5w.App\\Controller\\PaymentController::paymentSuccess()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'params' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'params' => '?',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\PaymentController::paymentSuccess()', $container);
    }
}
