<?php

namespace ContainerC24beQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPDFEnvoieMailsendAllPdfsService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.9dMfL4L.App\Controller\PDF_Envoie_Mail::sendAllPdfs()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9dMfL4L.App\\Controller\\PDF_Envoie_Mail::sendAllPdfs()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'utilisateurRepo' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
            'uisRepo' => ['privates', 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository', 'getUtilisateurInstitutionSessionModuleRepositoryService', true],
            'pdfGenerator' => ['privates', 'App\\Service\\PdfGenerator', 'getPdfGeneratorService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'utilisateurRepo' => 'App\\Repository\\UtilisateurRepository',
            'uisRepo' => 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository',
            'pdfGenerator' => 'App\\Service\\PdfGenerator',
            'logger' => '?',
            'mailer' => '?',
        ]))->withContext('App\\Controller\\PDF_Envoie_Mail::sendAllPdfs()', $container);
    }
}
