<?php

namespace ContainerC24beQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionModuleControllermodifierUtilisateurInstitutionSessionModuleService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.VxWxTIF.App\Controller\SessionModuleController::modifierUtilisateurInstitutionSessionModule()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VxWxTIF.App\\Controller\\SessionModuleController::modifierUtilisateurInstitutionSessionModule()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'utilisateurInstitutionSessionModuleRepository' => ['privates', 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository', 'getUtilisateurInstitutionSessionModuleRepositoryService', true],
            'sessionModuleRepository' => ['privates', 'App\\Repository\\SessionModuleRepository', 'getSessionModuleRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'utilisateurInstitutionSessionModuleRepository' => 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository',
            'sessionModuleRepository' => 'App\\Repository\\SessionModuleRepository',
            'em' => '?',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\SessionModuleController::modifierUtilisateurInstitutionSessionModule()', $container);
    }
}
