<?php

namespace ContainerC24beQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriptionControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\SubscriptionController' shared autowired service.
     *
     * @return \App\Controller\SubscriptionController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SubscriptionController'] = $instance = new \App\Controller\SubscriptionController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\SubscriptionController', $container));

        return $instance;
    }
}
