<?php

namespace ContainerC24beQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionModuleControllermodifierModuleService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.RvrrnGg.App\Controller\SessionModuleController::modifierModule()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RvrrnGg.App\\Controller\\SessionModuleController::modifierModule()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'moduleRepository' => ['privates', 'App\\Repository\\ModuleRepository', 'getModuleRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'moduleRepository' => 'App\\Repository\\ModuleRepository',
            'em' => '?',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\SessionModuleController::modifierModule()', $container);
    }
}
