<?php

namespace ContainerC24beQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateurInstitutionRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\UtilisateurInstitutionRepository' shared autowired service.
     *
     * @return \App\Repository\UtilisateurInstitutionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\UtilisateurInstitutionRepository'] = new \App\Repository\UtilisateurInstitutionRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
