<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC24beQx\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC24beQx/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerC24beQx.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerC24beQx\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerC24beQx\App_KernelDevContainer([
    'container.build_hash' => 'C24beQx',
    'container.build_id' => 'c6619fda',
    'container.build_time' => 1751405649,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC24beQx');
